global:
  resolve_timeout: 5m

route:
  group_by: ['VNFC']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'vespa'
receivers:
- name: 'vespa'
  webhook_configs:
  - url: 'http://localhost:9095/alerts'
